[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Rens Hamburger", email = "renshamburger@gmail.com"},
]
dependencies = []
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}

